# Project
site_name: Open Energy Family Compendium
site_url: 
site_description: Write your documentation in Markdown and create a static page for your developer and user community
docs_dir: 'kompendium'

# Configuration
theme:
  name: material
  logo: img/OEP_Energy_Family_04.png
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - toc.follow

# extensions 
markdown_extensions:
  - admonition
  - toc:
      permalink: 💙

# Customization
extra:
  generator: false

extra_css:
  - css/extra.css

# Navigation
nav:
  - Home: index.md
  - Open Energy Family:
    - Overview: open-energy-family/index.md
    - Knowledge transfer: open-energy-family/knowledge-transfer.md
    - Open Energy Platform: open-energy-family/open-energy-platform.md
    - Open Energy Database: open-energy-family/open-energy-database.md
    - Ontologie: open-energy-family/ontologie.md
    - Workflow automation for Datapreprocessing: open-energy-family/open-process-integration.md
    - Community management: open-energy-family/comunity-management.md
    - Softwaretools: 
      - open-energy-family/softwaretools/index.md
      - oedialect: open-energy-family/softwaretools/oedialect.md
      - oem2orm: open-energy-family/softwaretools/oem2orm.md
      - oep-client: open-energy-family/softwaretools/oep-client.md
      - omi: open-energy-family/softwaretools/omi.md
      - saio: open-energy-family/softwaretools/saio.md
    - Specification and Templates: 
      - open-energy-family/templates-and-specification/index.md
      - Factsheets: open-energy-family/templates-and-specification/factsheets.md
      - Open Energy Datamodel: open-energy-family/templates-and-specification/open-energy-datamodel.md
      - Open Energy Metadata: open-energy-family/templates-and-specification/open-energy-metadata.md
  
