# Project
site_name: Open Energy Family Compendium
site_url: 
site_description: Write your documentation in Markdown and create a static page for your developer and user community
docs_dir: 'kompendium'

# Configuration
theme:
  name: material
  logo: img/OEP_Energy_Family_04.png
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - toc.follow

# extensions 
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: 💙

# Customization
extra:
  generator: false

extra_css:
  - css/extra.css

# Navigation
nav:
  - Home: index.md
  - Open Energy Family:
    - Overview: open-energy-family/index.md
    - Collaboration: open-energy-family/collaboration.md
    - Community management: open-energy-family/comunity-management.md
    - Knowledge transfer: open-energy-family/knowledge-transfer.md
    - Knowledge representation: 
      - open-energy-family/ontology/index.md
      - Open Energy Ontology: open-energy-family/ontology/oeo.md 
      - Open Energy Knowledgegraph: open-energy-family/ontology/oekg.md #database own section?
    - Software products: 
      - open-energy-family/software-products/index.md
      - Open Energy Platform: open-energy-family/software-products/open-energy-platform.md
      - Open Energy Database: open-energy-family/software-products/open-energy-database.md #database own section?
      - Open Energy Databus: open-energy-family/software-products/open-energy-databus.md
      - Software tools: open-energy-family/software-products/software-tools.md
    - Specification and Templates: 
      - open-energy-family/templates-and-specification/index.md
      - Factsheets: open-energy-family/templates-and-specification/factsheets.md
      - Open Energy Datamodel: open-energy-family/templates-and-specification/open-energy-datamodel.md
      - Open Energy Metadata: open-energy-family/templates-and-specification/open-energy-metadata.md
    - Datapreprocessing and workflowautomation: open-energy-family/open-process-integration.md
  